### ISSUE TITLE
Toast with QApplication/QSystemTrayIcon instead of QMainWindow

### ISSUE THREAD

**Issue by abrichr** [niklashenning/pyqttoast#9]
Thank you for the excellent work!

Is it possible to use with a `QSystemTrayIcon` as the parent?

Passing in a `QApplication`:
```
TypeError: 'PySide6.QtWidgets.QDialog.__init__' called with wrong argument types:
  PySide6.QtWidgets.QDialog.__init__(QApplication)
Supported signatures:
  PySide6.QtWidgets.QDialog.__init__(Optional[PySide6.QtWidgets.QWidget] = None, PySide6.QtCore.Qt.WindowType = Default(Qt.WindowFlags))
```
Passing in a `QSystemTrayIcon`:
```
TypeError: 'PySide6.QtWidgets.QDialog.__init__' called with wrong argument types:
  PySide6.QtWidgets.QDialog.__init__(QSystemTrayIcon)
Supported signatures:
  PySide6.QtWidgets.QDialog.__init__(Optional[PySide6.QtWidgets.QWidget] = None, PySide6.QtCore.Qt.WindowType = Default(Qt.WindowFlags))
```

I would love to use `pyqt-toast`, but without a main window.

**Comment by abrichr** [comment]
Workaround:
```
        self.main_window = QMainWindow()
        self.main_window.setWindowFlags(Qt.WindowType.Tool | Qt.WindowType.FramelessWindowHint)
        self.main_window.resize(1, 1)  # Minimal size
        self.main_window.move(0, 0)  # Position on the screen
        toast = Toast(self.main_window)
```

**Comment by niklashenning** [comment]
Hi, thanks for opening this issue.

You currently have to pass a `QWidget` as a parent, so unfortunately, passing something like `QSystemTrayIcon` or `QApplication` doesn't work in this version. I did it this way since I needed a parent widget to implement always showing the toast on the screen that the window is currently on.

However, the toast could work perfectly fine with no parent, so I started making some changes, and now it also works without any parent, as long as there is a QApplication running. I still have to make a few adjustments and add some other stuff (like the option to manually set the screen where the toasts will be shown), and then I'll release the next version (v1.2.0) with those changes.

For now, I would've suggested the same workaround.
